In [1]:
#coding=utf-8
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
import numpy as np

In [2]:
#用来读取tfrecord数据
#"./Records/output.tfrecords"
def read_and_decode(filename): 
    # 读取文件。
    reader = tf.TFRecordReader()
    filename_queue = tf.train.string_input_producer([filename])
    #前面的_,是用来接受参数的read()%%!方法有两个返回参数
    _,serialized_example = reader.read(filename_queue)

    # 解析读取的样例。
    features = tf.parse_single_example(
        serialized_example,
        features={
            'image_raw':tf.FixedLenFeature([],tf.string),
            'label':tf.FixedLenFeature([],tf.int64)
        })

    decoded_images = tf.decode_raw(features['image_raw'],tf.uint8)
    labels = tf.cast(features['label'],tf.int32)
    retyped_images = tf.cast(decoded_images, tf.float32)
    # pixels = tf.cast(features['pixels'],tf.int32)
    images = tf.reshape(retyped_images,shape=[64,64,3])
    return images,labels

#用来返回batch
def createBatch(filename,batchsize):
    images, labels = read_and_decode(filename)
    min_after_dequeue = 500
    batch_size = batchsize
    capacity = min_after_dequeue + 3 * batch_size

    image_batch, label_batch = tf.train.shuffle_batch([images, labels], 
                                                        batch_size=batch_size, 
                                                        capacity=capacity, 
                                                        min_after_dequeue=min_after_dequeue)
    return image_batch, label_batch


In [3]:
#打印出batch
image_batch, label_batch= createBatch("./Records/output.tfrecords", 100)
sess = tf.Session()

# 启动多线程处理输入数据。
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess,coord=coord)

print sess.run(image_batch)
print sess.run(label_batch)

[[[[  55.   54.   50.]
   [  55.   54.   50.]
   [  58.   54.   51.]
   ..., 
   [  63.   63.   63.]
   [  57.   61.   62.]
   [  57.   61.   62.]]

  [[  55.   54.   50.]
   [  55.   54.   50.]
   [  57.   53.   52.]
   ..., 
   [  62.   62.   62.]
   [  58.   62.   63.]
   [  58.   62.   63.]]

  [[  54.   53.   51.]
   [  55.   54.   52.]
   [  57.   53.   52.]
   ..., 
   [  62.   62.   62.]
   [  59.   63.   64.]
   [  58.   62.   63.]]

  ..., 
  [[  41.   41.   41.]
   [  41.   41.   41.]
   [  41.   41.   39.]
   ..., 
   [  68.   69.   64.]
   [  65.   67.   64.]
   [  66.   68.   65.]]

  [[  40.   40.   40.]
   [  40.   40.   40.]
   [  40.   40.   38.]
   ..., 
   [  67.   66.   62.]
   [  62.   64.   61.]
   [  63.   65.   62.]]

  [[  40.   40.   40.]
   [  40.   40.   40.]
   [  40.   40.   38.]
   ..., 
   [  64.   63.   59.]
   [  63.   63.   61.]
   [  64.   64.   62.]]]


 [[[  23.   28.   24.]
   [  22.   27.   21.]
   [  23.   28.   22.]
   ..., 
   [  46.   47.   