In [1]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
import numpy as np

In [6]:
#用来读取tfrecord数据
#"./Records/output.tfrecords"
def read_and_decode(filename): 
    # 读取文件。
    reader = tf.TFRecordReader()
    filename_queue = tf.train.string_input_producer([filename])
    #前面的_,是用来接受参数的read()%%!方法有两个返回参数
    _,serialized_example = reader.read(filename_queue)

    # 解析读取的样例。
    features = tf.parse_single_example(
        serialized_example,
        features={
            'image_raw':tf.FixedLenFeature([],tf.string),
            'label':tf.FixedLenFeature([],tf.int64)
        })

    decoded_images = tf.decode_raw(features['image_raw'],tf.uint8)
    labels = tf.cast(features['label'],tf.int32)
    retyped_images = tf.cast(decoded_images, tf.float32)
    # pixels = tf.cast(features['pixels'],tf.int32)
    images = tf.reshape(retyped_images,shape=[64,64,3])
    return images,labels

#用来返回batch
def createBatch(filename,batchsize):
    images, labels = read_and_decode(filename)
    min_after_dequeue = 500
    batch_size = batchsize
    capacity = min_after_dequeue + 3 * batch_size

    image_batch, label_batch = tf.train.shuffle_batch([images, labels], 
                                                        batch_size=batch_size, 
                                                        capacity=capacity, 
                                                        min_after_dequeue=min_after_dequeue)
    return image_batch, label_batch

In [7]:
sess = tf.Session()

In [8]:
image_batch, label_batch= createBatch("./Records/output.tfrecords", 100)

In [9]:
# 启动多线程处理输入数据。
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess,coord=coord)

print sess.run(image_batch)

[[[[ 172.  189.  181.]
   [ 171.  186.  181.]
   [ 170.  187.  179.]
   ..., 
   [ 174.  191.  181.]
   [ 175.  191.  181.]
   [ 176.  189.  182.]]

  [[ 172.  187.  180.]
   [ 169.  184.  179.]
   [ 168.  185.  177.]
   ..., 
   [ 174.  191.  181.]
   [ 174.  190.  180.]
   [ 174.  189.  182.]]

  [[ 171.  186.  179.]
   [ 168.  183.  176.]
   [ 165.  182.  174.]
   ..., 
   [ 175.  191.  181.]
   [ 175.  190.  183.]
   [ 175.  190.  183.]]

  ..., 
  [[ 114.  119.  115.]
   [ 126.  131.  127.]
   [ 127.  133.  129.]
   ..., 
   [ 122.  143.  126.]
   [ 133.  154.  135.]
   [ 141.  160.  140.]]

  [[ 122.  131.  126.]
   [ 154.  163.  158.]
   [ 151.  160.  155.]
   ..., 
   [ 122.  142.  130.]
   [ 137.  155.  141.]
   [ 139.  158.  139.]]

  [[ 116.  140.  127.]
   [ 142.  166.  152.]
   [ 173.  195.  182.]
   ..., 
   [ 108.  136.  124.]
   [ 125.  157.  142.]
   [ 137.  169.  148.]]]


 [[[  40.   48.   51.]
   [  49.   57.   60.]
   [  50.   57.   63.]
   ..., 
   [ 154.  167.  1